default:
  image: node:latest

stages:
  - deploy

publish-npm:
  stage: deploy
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm build
    - echo "@flamel-ai:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - pnpm publish
